---
- name: Add new connect  in in-memory Inventory
  hosts: all
  gather_facts: false
  tasks:
    - name: "Change first-run kafka_connect Group Name"
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: "kafka_connect:"
        line: "kafka_connect1:"
      delegate_to: 127.0.0.1
      run_once: true

    - name: "Change kafka_connect2 group Name to kafka_connect which has newly added hosts as well"
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: "kafka_connect2:"
        line: "kafka_connect:"
      delegate_to: 127.0.0.1
      run_once: true
    
    - name: refresh Inventory
      meta: refresh_inventory


- name: Converge
  import_playbook: confluent.platform.all

