---
- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - name: Check line ksql cluster2
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ks2.url
        expected_value: http://ksql2:8088
    - name: Check advertised url default
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ks1.advertised.url
        expected_value: https://ksql1:8088
    - name: Check advertised url
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ks2.advertised.url
        expected_value: http://ksql2.confluent:8088

- name: Add new KSQL nodes in in-memory inventory
  hosts: all
  gather_facts: false
  tasks:
    - name: "Add new KSQL Nodes to ks2 cluster"
      add_host:
        hostname: ksql3
        ansible_connection: community.docker.docker
        groups:
          - ksql
          - ks2
        tag: ksql
    - name: "Add new KSQL Nodes to ks1 cluster"
      add_host:
        hostname: ksql4
        
        groups:
          - ksql
          - ks1
        tag: ksql

- name: Converge
  import_playbook: confluent.platform.all
