- name: Add new KSQL nodes in in-memory inventory
  hosts: all
  gather_facts: false
  tasks:
    - name: "Add new KSQL Nodes"
      add_host:
        hostname: ksql3
        ansible_connection: community.docker.docker
        groups: 
          - ksql
          - ks2
        tag: ksql

    - name: "Add new KSQL Nodes"
      add_host:
        hostname: ksql4
        ansible_connection: community.docker.docker
        groups: 
          - ksql
          - ks1
        tag: ksql

- name: Converge
  import_playbook: confluent.platform.all
  vars:
    required_total_memory_mb_zookeeper: 100
    required_total_memory_mb_ksql: 100
    required_total_memory_mb_kafka_broker: 100
    required_total_memory_mb_kafka_connect: 100
    required_total_memory_mb_kafka_rest: 100
    required_total_memory_mb_kafka_connect_replicator: 100
    required_total_memory_mb_control_center: 100
    required_total_memory_mb_schema_registry: 100
