---
### Validates that Kafka Connect Cluster1 is running with a valid connector.
### Validates that Kafka Connect Cluster2 is running with a valid connector.
### Validates that Kafka Connect Cluster3 is running without any connectors.
### Validates that two KSQL clusters are running.
### Validates that Control Center can connect to each Kafka Connect Cluster.
### Validates that Control Center Can connect to each KSQL cluster.

- name: Verify - ksql
  hosts: ksql1
  gather_facts: false
  tasks:
    - name: Check line properties file
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ksql.service.id
        expected_value: ksql1_

- name: Verify - ksql
  hosts: ksql2
  gather_facts: false
  tasks:
    - name: Check line properties file
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ksql.service.id
        expected_value: ksql2_

- name: Verify - ksql
  hosts: ksql3
  gather_facts: false
  tasks:
    - name: Check line properties file
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ksql.service.id
        expected_value: ksql2_

- name: Verify - ksql
  hosts: ksql4
  gather_facts: false
  tasks:
    - name: Check line properties file
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ksql.service.id
        expected_value: ksql1_

    - name: Get ClusterID and ServiceID for ksql1
      uri:
        url: "https://ksql1:8088"
        status_code: 200
        validate_certs: false
        client_cert: /var/ssl/private/ksql.crt
        client_key: /var/ssl/private/ksql.key
      register: ksql1_response

    - name: Get ClusterID and ServiceID for ksql2
      uri:
        url: "http://ksql2:8088"
        status_code: 200
      register: ksql2_response

    - name: Get ClusterID and ServiceID for ksql3
      uri:
        url: "http://ksql3:8088"
        status_code: 200
      register: ksql3_response

    - name: Get ClusterID and ServiceID for ksql4
      uri:
        url: "https://ksql4:8088"
        status_code: 200
        validate_certs: false
        client_cert: /var/ssl/private/ksql.crt
        client_key: /var/ssl/private/ksql.key
      register: ksql4_response

    - name: Validate kafka-Cluster ID and ksql-clusterid
      assert:
        that:
          - "ksql1_response.json.KsqlServerInfo.kafkaClusterId == ksql2_response.json.KsqlServerInfo.kafkaClusterId  == ksql3_response.json.KsqlServerInfo.kafkaClusterId  == ksql4_response.json.KsqlServerInfo.kafkaClusterId"
          - "ksql1_response.json.KsqlServerInfo.ksqlServiceId == ksql4_response.json.KsqlServerInfo.ksqlServiceId == 'ksql1_'"
          - "ksql2_response.json.KsqlServerInfo.ksqlServiceId == ksql3_response.json.KsqlServerInfo.ksqlServiceId == 'ksql2_'"

- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - name: Check line multi ksql line
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ks1.ssl.truststore.location
        expected_value: /var/ssl/private/control_center.truststore.jks

    - name: Check line ksql cluster2
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ks2.url
        expected_value: http://ksql2:8088,http://ksql3:8088

    - name: Check line connect cluster2
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.connect.connect-syslog.cluster
        expected_value: http://kafka-connect1:8083,http://kafka-connect2:8083,http://kafka-connect3:8083

    - name: Check advertised url default
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ks1.advertised.url
        expected_value: https://ksql1:8088,https://ksql4:8088

    - name: Check advertised url
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ks2.advertised.url
        expected_value: http://ksql2.confluent:8088,http://ksql3.confluent:8088
