---
- name: Update inventory to have ssl and zookeeper ssl flipped
  hosts: all
  gather_facts: false
  tasks:
    - name: "Change ssl_enabled and zookeeper_ssl_enabled variables"
      lineinfile:
        path: "{{inventory_dir}}/group_vars/all"
        regexp: '^zookeeper_(.*)_later:(.*)$'
        insertafter: '^zookeeper_(.*)$'
        line: 'zookeeper_ssl_enabled: true'
      delegate_to: 127.0.0.1
    - name: "Change ssl_enabled and zookeeper_ssl_enabled variables"
      lineinfile:
        path: "{{inventory_dir}}/group_vars/all"
        regexp: '^zookeeper_(.*)_later:(.*)$'
        insertafter: '^zookeeper_(.*)$'
        line: 'zookeeper_client_authentication_type: mtls'
      delegate_to: 127.0.0.1

    - name: Refresh Inventory
      meta: refresh_inventory

    - set_fact:
        zookeeper_ssl_enabled: true
        deployment_strategy: rolling
        zokeeper_client_authentication_type: mtls

- name: Converge
  import_playbook: confluent.platform.all
